import { Box } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';
import CardItem from '../components/CardItem/CardItem';
const Home: NextPage = () => {
  return (
    <Box py={'100px'} px='100px'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardItem />
    </Box>
  );
};

export default Home;
